#ifndef SM64AP_H
#define SM64AP_H

#include <stdbool.h>

#ifdef __cplusplus
#define AP_EXTERN_C extern "C"
#else
#define AP_EXTERN_C extern
#endif

#ifdef __cplusplus
extern "C" {
    #include "types.h"
}
#else
#include "types.h"
#endif

#define SM64AP_ID_OFFSET 3626000
#define SM64AP_ITEMID_STAR SM64AP_ID_OFFSET
#define SM64AP_ID_KEY1 (SM64AP_ID_OFFSET+178)
#define SM64AP_ID_KEY2 (SM64AP_ID_KEY1+1)
#define SM64AP_ID_KEYPROG (SM64AP_ID_KEY2+1)
#define SM64AP_ID_WINGCAP (SM64AP_ID_KEYPROG+1)
#define SM64AP_ID_METALCAP (SM64AP_ID_WINGCAP+1)
#define SM64AP_ID_VANISHCAP (SM64AP_ID_METALCAP+1)
#define SM64AP_ITEMID_1UP (SM64AP_ID_VANISHCAP+1)

#define SM64AP_ABILITY_OFFSET (SM64AP_ITEMID_1UP+1)
#define SM64AP_ID_DOUBLEJUMP (SM64AP_ABILITY_OFFSET)
#define SM64AP_ID_TRIPLEJUMP (SM64AP_ABILITY_OFFSET+1)
#define SM64AP_ID_LONGJUMP (SM64AP_ABILITY_OFFSET+2)
#define SM64AP_ID_BACKFLIP (SM64AP_ABILITY_OFFSET+3)
#define SM64AP_ID_SIDEFLIP (SM64AP_ABILITY_OFFSET+4)
#define SM64AP_ID_WALLKICK (SM64AP_ABILITY_OFFSET+5)
#define SM64AP_ID_DIVE (SM64AP_ABILITY_OFFSET+6)
#define SM64AP_ID_GROUNDPOUND (SM64AP_ABILITY_OFFSET+7)
#define SM64AP_ID_KICK (SM64AP_ABILITY_OFFSET+8)
#define SM64AP_ID_CLIMB (SM64AP_ABILITY_OFFSET+9)
#define SM64AP_ID_LEDGEGRAB (SM64AP_ABILITY_OFFSET+10)

#define SM64AP_ID_CANNONUNLOCK(x) (SM64AP_ID_OFFSET+200+x)
#define SM64AP_ID_PAINTINGUNLOCK(x) (SM64AP_ID_OFFSET+230+x)
#define SM64AP_ID_ABILITY(x) (SM64AP_ABILITY_OFFSET+x)
// Reserving some room for coins, if needed
// Nice filler
#define SM64AP_ID_1_HEALTH_PIP   (SM64AP_ID_OFFSET+1750)
#define SM64AP_ID_2_HEALTH_PIP   (SM64AP_ID_OFFSET+1751)
#define SM64AP_ID_3_HEALTH_PIP   (SM64AP_ID_OFFSET+1752)
#define SM64AP_ID_4_HEALTH_PIP   (SM64AP_ID_OFFSET+1753)
#define SM64AP_ID_FULL_REFILL    (SM64AP_ID_OFFSET+1754)
// Traps
#define SM64AP_ID_BONK_TRAP      (SM64AP_ID_OFFSET+1760)
#define SM64AP_ID_FIRE_TRAP      (SM64AP_ID_OFFSET+1761)
#define SM64AP_ID_ELEC_TRAP      (SM64AP_ID_OFFSET+1762)
#define SM64AP_ID_CHUCK_TRAP     (SM64AP_ID_OFFSET+1763)
#define SM64AP_ID_SPIN_TRAP      (SM64AP_ID_OFFSET+1764)
#define SM64AP_ID_GUST_TRAP      (SM64AP_ID_OFFSET+1765)


#define SM64AP_LOCATIONID_BOARDBOWSERSSUB (SM64AP_ID_OFFSET + 56)
#define SM64AP_LOCATIONID_BASEMENTTOAD (SM64AP_ID_OFFSET + 168)
#define SM64AP_LOCATIONID_SECONDFLOORTOAD (SM64AP_LOCATIONID_BASEMENTTOAD + 1)
#define SM64AP_LOCATIONID_THIRDFLOORTOAD (SM64AP_LOCATIONID_SECONDFLOORTOAD + 1)
#define SM64AP_LOCATIONID_MIPS1 (SM64AP_LOCATIONID_THIRDFLOORTOAD + 1)
#define SM64AP_LOCATIONID_MIPS2 (SM64AP_LOCATIONID_MIPS1 + 1)
#define SM64AP_LOCATIONID_YOSHI (SM64AP_ID_OFFSET + 244)

#define SM64AP_NUM_LOCS 245

#define SM64AP_NUM_ABILITIES 11
#define SM64AP_NUM_PAINTING_LOCKS 15

enum {
    SM64AP_FEATURE_BOB_KING_BOBOMB,
    SM64AP_FEATURE_BOB_KOOPA_THE_QUICK,
    SM64AP_FEATURE_BOB_BOBOMB_BUDDY,
    SM64AP_FEATURE_WF_WHOMP_KING,
    SM64AP_FEATURE_WF_FORTRESS,
    SM64AP_FEATURE_WF_BOBOMB_BUDDY,
    SM64AP_FEATURE_WF_HOOT,
    SM64AP_FEATURE_CCM_SNOWMANS_HEAD,
    SM64AP_FEATURE_CCM_BIG_PENGUIN,
    SM64AP_FEATURE_JRB_SUNKEN_SHIP,
    SM64AP_FEATURE_JRB_RAISED_SHIP,
    SM64AP_FEATURE_JRB_BOBOMB_BUDDY,
    SM64AP_FEATURE_JRB_JET_STREAM,
    SM64AP_FEATURE_JRB_UNAGI,
    SM64AP_FEATURE_LLL_KOOPA_SHELL,
    SM64AP_FEATURE_SSL_KLEPTO_STAR,
    SM64AP_FEATURE_THI_KOOPA_THE_QUICK,
    SM64AP_FEATURE_TTM_UKIKI,
    SM64AP_FEATURE_DDD_MANTA_RAY,
    SM64AP_FEATURE_DDD_BOWSERS_SUB,
    SM64AP_FEATURE_DDD_POLES,
    SM64AP_FEATURE_BBH_STAIRCASE,
    SM64AP_FEATURE_BBH_MERRY_GO_ROUND,
    SM64AP_NUM_FEATURES
};

#define SM64AP_FEATURE_OFFSET SM64AP_ID_PAINTINGUNLOCK(SM64AP_NUM_PAINTING_LOCKS)
#define SM64AP_ID_FEATURE(x) (SM64AP_FEATURE_OFFSET + (x))

#define SM64AP_CASTLE_KEY_FIRST_FLOOR 0
#define SM64AP_CASTLE_KEY_BASEMENT 1
#define SM64AP_CASTLE_KEY_BASEMENT_STAR 2
#define SM64AP_CASTLE_KEY_UPSTAIRS 3
#define SM64AP_CASTLE_KEY_50_STAR 4
#define SM64AP_CASTLE_KEY_70_STAR 5
#define SM64AP_NUM_CASTLE_KEYS 6

#define SM64AP_CASTLE_KEY_OFFSET (SM64AP_FEATURE_OFFSET + SM64AP_NUM_FEATURES)
#define SM64AP_ID_FIRST_FLOOR_KEY (SM64AP_CASTLE_KEY_OFFSET)
#define SM64AP_ID_BASEMENT_KEYPROG (SM64AP_CASTLE_KEY_OFFSET + 1)
#define SM64AP_ID_UPSTAIRS_KEYPROG (SM64AP_CASTLE_KEY_OFFSET + 2)
#define SM64AP_NUM_CASTLE_KEY_ITEMS 3

#define SM64AP_CASTLE_MISC_OFFSET (SM64AP_CASTLE_KEY_OFFSET + SM64AP_NUM_CASTLE_KEY_ITEMS)
#define SM64AP_ID_PROGRESSIVE_MIPS (SM64AP_CASTLE_MISC_OFFSET)
#define SM64AP_ID_WING_CAP_LIGHT (SM64AP_CASTLE_MISC_OFFSET + 1)
#define SM64AP_ID_BBH (SM64AP_CASTLE_MISC_OFFSET + 2)
#define SM64AP_ID_TOADS (SM64AP_CASTLE_MISC_OFFSET + 3)
#define SM64AP_ID_CASTLE_CANNON (SM64AP_CASTLE_MISC_OFFSET + 4)
#define SM64AP_ID_YOSHI (SM64AP_CASTLE_MISC_OFFSET + 5)
#define SM64AP_NUM_CASTLE_MISC_ITEMS 6

#define SM64AP_ID_BITFS 3626304

#define SM64AP_LEVEL_CAP_OFFSET (SM64AP_CASTLE_MISC_OFFSET + SM64AP_NUM_CASTLE_MISC_ITEMS)

enum {
    SM64AP_LEVEL_CAP_BOB_WING,
    SM64AP_LEVEL_CAP_CASTLE_WING,
    SM64AP_LEVEL_CAP_LLL_WING,
    SM64AP_LEVEL_CAP_SSL_WING,
    SM64AP_LEVEL_CAP_TOTWC_WING,
    SM64AP_LEVEL_CAP_WMOTR_WING,
    SM64AP_LEVEL_CAP_WF_METAL,
    SM64AP_LEVEL_CAP_JRB_METAL,
    SM64AP_LEVEL_CAP_HMC_METAL,
    SM64AP_LEVEL_CAP_DDD_METAL,
    SM64AP_LEVEL_CAP_WDW_METAL,
    SM64AP_LEVEL_CAP_COTMC_METAL,
    SM64AP_LEVEL_CAP_BITDW_METAL,
    SM64AP_LEVEL_CAP_BBH_VANISH,
    SM64AP_LEVEL_CAP_DDD_VANISH,
    SM64AP_LEVEL_CAP_SL_VANISH,
    SM64AP_LEVEL_CAP_VCUTM_VANISH,
    SM64AP_LEVEL_CAP_WDW_VANISH,
    SM64AP_NUM_LEVEL_CAPS
};

#define SM64AP_ID_LEVEL_CAP(x) (SM64AP_LEVEL_CAP_OFFSET + (x))

#define SM64AP_OBJECT_ITEM_OFFSET (SM64AP_LEVEL_CAP_OFFSET + SM64AP_NUM_LEVEL_CAPS)

enum {
    SM64AP_OBJECT_ITEM_HMC_SWIMMING_BEAST,
    SM64AP_OBJECT_ITEM_RR_CARPETS,
    SM64AP_OBJECT_ITEM_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_THI_WARP_PIPES,
    SM64AP_OBJECT_ITEM_CCM_BABY_PENGUINS,
    SM64AP_OBJECT_ITEM_SL_PENGUIN,
    SM64AP_OBJECT_ITEM_SSL_PYRAMID_ELEVATOR,
    SM64AP_OBJECT_ITEM_ROLLING_LOGS,
    SM64AP_OBJECT_ITEM_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_RESERVED_BITFS,
    SM64AP_OBJECT_ITEM_WDW_WATER_LEVEL_DIAMONDS,
    SM64AP_OBJECT_ITEM_BOB_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_WF_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_LLL_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_HMC_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_VCUTM_CHECKERBOARD_PLATFORMS,
    SM64AP_OBJECT_ITEM_LLL_ROLLING_LOGS,
    SM64AP_OBJECT_ITEM_TTM_ROLLING_LOGS,
    SM64AP_OBJECT_ITEM_BOB_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_HMC_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_WDW_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_RR_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_BITDW_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_BITS_PURPLE_SWITCHES,
    SM64AP_OBJECT_ITEM_TTC_SPINNERS,
    SM64AP_NUM_OBJECT_ITEMS
};

#define SM64AP_ID_OBJECT_ITEM(x) (SM64AP_OBJECT_ITEM_OFFSET + (x))

#define SM64AP_ID_HAT 3626320

#define SM64AP_CASTLE_DOOR_FIRST_FLOOR 0xF0
#define SM64AP_CASTLE_DOOR_BASEMENT_STAR 0xF1
#define SM64AP_CASTLE_DOOR_UPSTAIRS_50 0xF2
#define SM64AP_CASTLE_DOOR_UPSTAIRS_70 0xF3

#define SM64AP_ENTRANCE_ID(level, variant) ((level) * 10 + (variant))
#define SM64AP_ENTRANCE_WDW_LOW 1
#define SM64AP_ENTRANCE_WDW_MIDDLE 2
#define SM64AP_ENTRANCE_WDW_HIGH 3
#define SM64AP_WDW_LOW_ENTRY_MAX 1382.4f
#define SM64AP_WDW_HIGH_ENTRY_MIN 1600.0f
#define SM64AP_WDW_LOW_WATER_LEVEL 31
#define SM64AP_WDW_MIDDLE_WATER_LEVEL 1024
#define SM64AP_WDW_HIGH_WATER_LEVEL 2816
#define SM64AP_ENTRANCE_TTC_STOPPED 1
#define SM64AP_ENTRANCE_TTC_SLOW 2
#define SM64AP_ENTRANCE_TTC_RANDOM 3
#define SM64AP_ENTRANCE_TTC_FAST 4

//Init
AP_EXTERN_C void SM64AP_InitMW(const char*, const char*, const char*);
AP_EXTERN_C void SM64AP_InitSP(const char*);

// Local Stars, Keys and Caps
AP_EXTERN_C int SM64AP_GetStars();
AP_EXTERN_C int SM64AP_GetRequiredStars(int);
AP_EXTERN_C int SM64AP_GetCoinStarRequirement(int);
AP_EXTERN_C u32 SM64AP_CourseStarFlags(s32);
AP_EXTERN_C void SM64AP_RedirectWarp(s16*,s16*,s8*,s16*,s16*,bool,int,s32);
AP_EXTERN_C int SM64AP_EntranceToTTC();
AP_EXTERN_C void SM64AP_SetClockToTTCAction(int* action);
AP_EXTERN_C void SM64AP_SetClockToTTCState();
AP_EXTERN_C void SM64AP_SetTTCEntranceSpeed(int speed);
AP_EXTERN_C int SM64AP_GetTTCEntranceVariant();
AP_EXTERN_C s16 SM64AP_GetWDWEntranceWaterLevel(s16 vanillaWaterLevel);
AP_EXTERN_C s16 SM64AP_ResolveAreaMusic(s16 level, s16 area, s16 vanillaSeq);
AP_EXTERN_C bool SM64AP_CheckedLoc(int);
AP_EXTERN_C bool SM64AP_HaveKey1();
AP_EXTERN_C bool SM64AP_HaveKey2();
AP_EXTERN_C bool SM64AP_HaveCastleKey(int);
AP_EXTERN_C bool SM64AP_HaveProgressiveMips(int);
AP_EXTERN_C bool SM64AP_HaveWingCapLight();
AP_EXTERN_C bool SM64AP_HaveBBH();
AP_EXTERN_C bool SM64AP_HaveToads();
AP_EXTERN_C bool SM64AP_HaveCastleCannon();
AP_EXTERN_C bool SM64AP_HaveYoshi();
AP_EXTERN_C bool SM64AP_HaveBITFS();
AP_EXTERN_C bool SM64AP_HaveHat();
AP_EXTERN_C bool SM64AP_HatRestoreWithAnimationPending();
AP_EXTERN_C bool SM64AP_HatRestoreWithoutAnimationPending();
AP_EXTERN_C void SM64AP_HatRestoreComplete();
AP_EXTERN_C bool SM64AP_HaveCap(int);
AP_EXTERN_C bool SM64AP_HaveAnyCap(int);
AP_EXTERN_C int SM64AP_CountLevelCaps(int);
AP_EXTERN_C bool SM64AP_HaveGlobalCap(int);
AP_EXTERN_C bool SM64AP_ShowGlobalCapDisplay();
AP_EXTERN_C bool SM64AP_HaveCannon(int);
AP_EXTERN_C bool SM64AP_HaveFeature(int);
AP_EXTERN_C bool SM64AP_HaveObjectItem(int);
AP_EXTERN_C bool SM64AP_HaveObjectItemForCourse(int, int);
AP_EXTERN_C bool SM64AP_HaveLevelCapOrGlobal(int);
AP_EXTERN_C bool SM64AP_CollectedCourseStar(int, int);
AP_EXTERN_C bool SM64AP_ShouldSpawnLevelObject(s16, s16, s16, s16, s16, s16, u32, const void *);
AP_EXTERN_C bool SM64AP_ShouldCreateWhirlpool(s16, s16, s8, s8, s16, s16, s16, s16);
AP_EXTERN_C bool SM64AP_HavePainting(int);
AP_EXTERN_C bool SM64AP_PaintingRandoEnabled();
AP_EXTERN_C bool SM64AP_DeathLinkPending();
AP_EXTERN_C void SM64AP_DeathLinkClear();
AP_EXTERN_C void SM64AP_DeathLinkSend();

// Local Moves
AP_EXTERN_C bool SM64AP_CanDoubleJump();
AP_EXTERN_C bool SM64AP_CanTripleJump();
AP_EXTERN_C bool SM64AP_CanLongJump();
AP_EXTERN_C bool SM64AP_CanBackflip();
AP_EXTERN_C bool SM64AP_CanSideFlip();
AP_EXTERN_C bool SM64AP_CanWallKick();
AP_EXTERN_C bool SM64AP_CanDive();
AP_EXTERN_C bool SM64AP_CanGroundPound();
AP_EXTERN_C bool SM64AP_CanKick();
AP_EXTERN_C bool SM64AP_CanClimb();
AP_EXTERN_C bool SM64AP_CanLedgeGrab();

// Send Item
AP_EXTERN_C void SM64AP_SendByBoxID(int);
AP_EXTERN_C void SM64AP_SendItem(int);

// Print Next Message to Screen
AP_EXTERN_C void SM64AP_PrintNext();

// If an item exists on the stack, return it, otherwise 0
AP_EXTERN_C int64_t SM64AP_PopDelayedStack();

// Called on each Bowser stage completion, i is bowser index. Will send StoryComplete depending on completion option.
AP_EXTERN_C void SM64AP_FinishBowser(int i);

// Used to send and receive moat state
AP_EXTERN_C void SM64AP_SetMoatDrained();
AP_EXTERN_C bool SM64AP_MoatDrained();

// Check for switch state (used for initial switch state on level load)
AP_EXTERN_C bool SM64AP_PressedSwitch(int);

#undef AP_EXTERN_C

#endif
